apiVersion: v1
kind: Service # mendefinisikan kind service untuk komunikasi order-service, shipping-service dan rabbitmq
metadata:
  name: rabbitmq-service-internal # metadata nama yang digunakan
  labels:
    app: rabbitmq # label yang digunakan app rabbitmq
spec: # spesifikasi
  ports:
  - port: 5672 # port yang digunakan denga protocol TCP
    protocol: TCP
  #type: ClusterIP
  selector:
    app: rabbitmq # mendefinisikan selector app
