#Set apiversion 1
apiVersion: v1
kind: Service # Object type service untuk akses rabbitmq UI
metadata:
  #Set name & labels
  name: rabbitmq-service #set name objek service
  labels: #set label service
    app: rabbitmq # label app yang digunakan
#Set ports & Selector
spec: # spesifikasi
  ports:
  - port: 15672 # port yang digunakan 15672
    protocol: TCP #set protocol TCP
  type: NodePort # type port nodeport
  selector:
    app: rabbitmq # selector app adalah rabbitmq
